export const keywords = [
  { keyword: 'Artist', name: 'type-artist'},
  { keyword: 'Producer', name: 'type-producer'},
  { keyword: 'Brand', name: 'type-brand'},
  { keyword: 'Creator', name: 'type-creator'},
  { keyword: 'Light Theme', name: 'theme-dark'},
  { keyword: 'Dark Theme', name: 'theme-light'},
  { keyword: 'Neutral Palette', name: 'palette-neutral'},
  { keyword: 'Colorful Palette', name: 'palette-colorful'},
  { keyword: 'Brand Color', name: 'brand-color'},
  { keyword: 'Sans Fonts', name: 'fonts-sans'},
  { keyword: 'Serif Fonts', name: 'fonts-serif'},
  { keyword: 'Hybrid Fonts', name: 'fonts-hybrid'},
  { keyword: 'SVG Logo', name: 'logo-svg'},
  { keyword: 'HTML Text Logo', name: 'logo-html'},
  { keyword: 'Wordmark', name: 'logo-wordmark'},
  { keyword: 'Brandmark', name: 'logo-brandmark'},
  { keyword: 'Micro Animations', name: 'animations-micro'},
  { keyword: 'Big Animations', name: 'animations-big'},
  { keyword: 'Scroll Reveal', name: 'animations-scroll'},
  { keyword: 'Parallax', name: 'animations-parallax'},
  { keyword: 'Single Page', name: 'pages-spa'},
  { keyword: 'Multi Page', name: 'pages-mpa'},
  { keyword: 'Open Nav', name: 'open-nav'},
  { keyword: 'Collapsed Nav', name: 'collapsed-nav'},
  { keyword: 'Hybrid Nav', name: 'hybrid-nav'},
  { keyword: 'CTA Listen', name: 'cta-listen'},
  { keyword: 'CTA Shop', name: 'cta-shop'},
  { keyword: 'CTA Other', name: 'cta-other'},
  { keyword: 'Video Hero', name: 'hero-video'},
  { keyword: 'Photo Hero', name: 'hero-photo'},
  { keyword: 'Abstract Hero', name: 'hero-abstract'},
  { keyword: 'Tour Dates', name: 'hero-abstract'},
  { keyword: 'Music', name: 'hero-abstract'},
  { keyword: 'Video', name: 'hero-abstract'},
  { keyword: 'About', name: 'hero-abstract'},
  { keyword: 'Photos', name: 'hero-abstract'},
  { keyword: 'Internal Store', name: 'store-internal'},
  { keyword: 'External Store', name: 'store-external'},
  { keyword: 'Contact Form', name: 'contact-form'},
  { keyword: 'Mailing List', name: 'mailing-list'},
  { keyword: 'Minimal', name: 'style-minimal'},
  { keyword: 'Busy', name: 'style-busy'},
  { keyword: 'Clean', name: 'style-clean'},
  { keyword: 'Chaotic', name: 'style-chaotic'},
  { keyword: 'Bright', name: 'style-bright'},
  { keyword: 'Moody', name: 'style-moody'},
  { keyword: 'Exceptional', name: 'exceptional'},
  { keyword: 'Could Be Better', name: 'could-be-better'},
]